In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
data = pd.read_csv("D:\Twitter-entity-sentiment-analysis\DATA\Twitter-sentiment analysis.csv")

In [3]:
data

2401  Borderlands  Positive  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74676  9200       Nvidia  Positive   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
0      I am coming to the borders and I will kill you...     
1      im getting on borderlands and i will kill you ...     
2      im coming on borderlands and i will murder you...     
3      im getting on borderlands 2 and i will murder ...     
4      im getting into borderlands and i can murder y...     
...                                                  ...     
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partition is ...     
74678  Just realized the windows partition of my Mac ...     
74679  Just realized between the windows partition of...     
74680  Just like the windows partition of my Mac is l...     

[74681 rows x 4 columns]

In [4]:
data.columns= ['Tweet_ID','Entity','Sentiment','Text']

In [5]:
data

Tweet_ID       Entity Sentiment  \
0          2401  Borderlands  Positive   
1          2401  Borderlands  Positive   
2          2401  Borderlands  Positive   
3          2401  Borderlands  Positive   
4          2401  Borderlands  Positive   
...         ...          ...       ...   
74676      9200       Nvidia  Positive   
74677      9200       Nvidia  Positive   
74678      9200       Nvidia  Positive   
74679      9200       Nvidia  Positive   
74680      9200       Nvidia  Positive   

                                                    Text  
0      I am coming to the borders and I will kill you...  
1      im getting on borderlands and i will kill you ...  
2      im coming on borderlands and i will murder you...  
3      im getting on borderlands 2 and i will murder ...  
4      im getting into borderlands and i can murder y...  
...                                                  ...  
74676  Just realized that the Windows partition of my...  
74677  Just realized that my Mac window partition is ...  
74678  Just realized the windows partition of my Mac ...  
74679  Just realized between the windows partition of...  
74680  Just like the windows partition of my Mac is l...  

[74681 rows x 4 columns]

In [6]:
data.isnull().sum()

Tweet_ID       0
Entity         0
Sentiment      0
Text         686
dtype: int64

In [7]:
data.dropna(axis=0,inplace=True)

In [8]:
data.isnull().sum()

Tweet_ID     0
Entity       0
Sentiment    0
Text         0
dtype: int64

In [9]:
data.shape

(73995, 4)

In [10]:
data.duplicated().sum()

2341

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data.duplicated().sum()

0

In [13]:
data["Sentiment"].unique()

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [15]:
data["Sentiment"] = encoder.fit_transform(data["Sentiment"])

In [16]:
data["Sentiment"].unique()

array([3, 2, 1, 0])

In [17]:
data

Tweet_ID       Entity  Sentiment  \
0          2401  Borderlands          3   
1          2401  Borderlands          3   
2          2401  Borderlands          3   
3          2401  Borderlands          3   
4          2401  Borderlands          3   
...         ...          ...        ...   
74676      9200       Nvidia          3   
74677      9200       Nvidia          3   
74678      9200       Nvidia          3   
74679      9200       Nvidia          3   
74680      9200       Nvidia          3   

                                                    Text  
0      I am coming to the borders and I will kill you...  
1      im getting on borderlands and i will kill you ...  
2      im coming on borderlands and i will murder you...  
3      im getting on borderlands 2 and i will murder ...  
4      im getting into borderlands and i can murder y...  
...                                                  ...  
74676  Just realized that the Windows partition of my...  
74677  Just realized that my Mac window partition is ...  
74678  Just realized the windows partition of my Mac ...  
74679  Just realized between the windows partition of...  
74680  Just like the windows partition of my Mac is l...  

[71654 rows x 4 columns]

In [18]:
data.drop(columns=["Tweet_ID","Entity"],inplace=True)

In [19]:
data2 = data.head(30000)

In [20]:
data2.shape

(30000, 2)

In [21]:
data2["Text"] = data2["Text"].str.lower()

In [22]:
data2

Sentiment                                               Text
0              3  i am coming to the borders and i will kill you...
1              3  im getting on borderlands and i will kill you ...
2              3  im coming on borderlands and i will murder you...
3              3  im getting on borderlands 2 and i will murder ...
4              3  im getting into borderlands and i can murder y...
...          ...                                                ...
31344          1  league of legends sucks, play rogue company! f...
31345          1  лига отсосов, играй в разбойничу компания!!!!!...
31346          1  league of legends guys, play rogue company! wa...
31347          1  league of legends sucks, to play rogue company...
31348          1  league of legends and, play rogue company! eve...

[30000 rows x 2 columns]

In [23]:
import re

def remove_htm(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r'',text)

In [24]:
data2["Text"] = data2["Text"].apply(remove_htm)

In [25]:
data2

Sentiment                                               Text
0              3  i am coming to the borders and i will kill you...
1              3  im getting on borderlands and i will kill you ...
2              3  im coming on borderlands and i will murder you...
3              3  im getting on borderlands 2 and i will murder ...
4              3  im getting into borderlands and i can murder y...
...          ...                                                ...
31344          1  league of legends sucks, play rogue company! f...
31345          1  лига отсосов, играй в разбойничу компания!!!!!...
31346          1  league of legends guys, play rogue company! wa...
31347          1  league of legends sucks, to play rogue company...
31348          1  league of legends and, play rogue company! eve...

[30000 rows x 2 columns]

In [26]:

import re

def remove_urls(text):
    # Define the regular expression pattern for URLs
    url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    # Substitute URLs with an empty string
    return re.sub(url_pattern, '', text)

In [27]:
data2["Text"] = data2["Text"].apply(remove_urls)

In [28]:
data2

Sentiment                                               Text
0              3  i am coming to the borders and i will kill you...
1              3  im getting on borderlands and i will kill you ...
2              3  im coming on borderlands and i will murder you...
3              3  im getting on borderlands 2 and i will murder ...
4              3  im getting into borderlands and i can murder y...
...          ...                                                ...
31344          1  league of legends sucks, play rogue company! f...
31345          1  лига отсосов, играй в разбойничу компания!!!!!...
31346          1  league of legends guys, play rogue company! wa...
31347          1  league of legends sucks, to play rogue company...
31348          1  league of legends and, play rogue company! eve...

[30000 rows x 2 columns]

In [29]:
import string

# Function to remove punctuation from a string
def remove_punctuation(text):
    if isinstance(text, str):
        return text.translate(str.maketrans('', '', string.punctuation))
    return text

In [30]:
data2["Text"] = data2["Text"].apply(remove_punctuation)

In [31]:
data2.tail(50)

Sentiment                                               Text
31299          1  16 leagueoflegends riotgames am i the only one...
31300          1  leagueoflegends q am i the only one who since ...
31301          1                     holy shit what world are we in
31302          1                       holy shots what are we in we
31303          1                        holi shit what in the world
31304          1                     holy shit what world who we in
31305          1        42 holy shit what world i are we getting in
31306          1                    holy business what world are we
31307          0                   scratch that cancelled as well  
31308          0                             scratch that cancel it
31309          0                            scrape it cancel it too
31310          0                     scratch bowl cancelled as well
31311          0             and scratch that cancelled off as well
31312          0                 scratch that cancelled as expected
31313          0  tweeting this because i lost 200 on the stock ...
31314          0  im tweeting this because i lost 200 on the sto...
31315          0  twitter is because i lost 200 on the stock mar...
31316          0  tweeting this because i lost 200 on the stock ...
31317          0  tweeting this happened because i lost  200 on ...
31318          0  tweeting below that i missed 200 on the stock ...
31319          2  i actually want to play pokémon league of lege...
31320          2  i actually want to play a pokémon league of le...
31321          2  i actually want to play pokémon league so bad ...
31322          2  i actually want to play pokémon league of lege...
31323          2  while i might actually want to help play pokém...
31324          2  i actually make them play pokemon league of le...
31325          2                               check out my video  
31326          2                            take a look at my video
31327          2                                     watch my video
31328          2                             check out my slideshow
31329          2                                 check out my video
31330          2                                pulled out my video
31331          2  miss fortune vs tahm kench  leagueofhentaicomm...
31332          2  miss fortune vs tahm kench  leagueofhentaicom ...
31333          2  miss foundation vs femme kench  leagueofhentai...
31334          2  miss fortune vs tahm  courtesyofhentaicommissf...
31335          2  2016 miss fortune taylor vs tahm kench  v leag...
31336          2    of fortune vs k da  dateofhentaicommissfortunev
31337          2                               check out my video  
31338          2                            take a look at my video
31339          2                                     watch my video
31340          2                                check out my photos
31341          2                              check out my dj video
31342          2                                check out its video
31343          1  league of legends sucks play rogue company way...
31344          1  league of legends sucks play rogue company far...
31345          1           лига отсосов играй в разбойничу компания
31346          1  league of legends guys play rogue company way ...
31347          1  league of legends sucks to play rogue company ...
31348          1  league of legends and play rogue company even ...

In [32]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Download stopwords if not already done
nltk.download('stopwords')
nltk.download('punkt')

# Load the stop words from nltk
stop_words = set(stopwords.words('english'))

def remove_stop_words(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    # Filter out the stop words
    filtered_words = [word for word in words if word.lower() not in stop_words]
    # Join the words back into a string
    filtered_text = ' '.join(filtered_words)
    return filtered_text

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [33]:
data2["Text"] = data2["Text"].apply(remove_stop_words)

In [34]:
data2

Sentiment                                               Text
0              3                                coming borders kill
1              3                        im getting borderlands kill
2              3                       im coming borderlands murder
3              3                    im getting borderlands 2 murder
4              3                      im getting borderlands murder
...          ...                                                ...
31344          1  league legends sucks play rogue company far be...
31345          1           лига отсосов играй в разбойничу компания
31346          1  league legends guys play rogue company way better
31347          1  league legends sucks play rogue company way be...
31348          1      league legends play rogue company even better

[30000 rows x 2 columns]

In [37]:
data2

Sentiment                                               Text
0              3                                coming borders kill
1              3                        im getting borderlands kill
2              3                       im coming borderlands murder
3              3                    im getting borderlands 2 murder
4              3                      im getting borderlands murder
...          ...                                                ...
31344          1  league legends sucks play rogue company far be...
31345          1           лига отсосов играй в разбойничу компания
31346          1  league legends guys play rogue company way better
31347          1  league legends sucks play rogue company way be...
31348          1      league legends play rogue company even better

[30000 rows x 2 columns]

In [38]:
import pandas as pd
import re



# Function to remove emojis
def remove_emojis(text):
    # Define a regex pattern to match emojis
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F700-\U0001F77F"  # alchemical symbols
        u"\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        u"\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        u"\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        u"\U0001FA00-\U0001FA6F"  # Chess Symbols
        u"\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        u"\U00002702-\U000027B0"  # Dingbats
        u"\U000024C2-\U0001F251" 
        "]+", flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)




In [39]:
data2["Text"] = data2["Text"].apply(remove_emojis)

In [40]:
data2

Sentiment                                               Text
0              3                                coming borders kill
1              3                        im getting borderlands kill
2              3                       im coming borderlands murder
3              3                    im getting borderlands 2 murder
4              3                      im getting borderlands murder
...          ...                                                ...
31344          1  league legends sucks play rogue company far be...
31345          1           лига отсосов играй в разбойничу компания
31346          1  league legends guys play rogue company way better
31347          1  league legends sucks play rogue company way be...
31348          1      league legends play rogue company even better

[30000 rows x 2 columns]

In [41]:
data2.shape

(30000, 2)

In [42]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(data2.Text,data2.Sentiment,test_size = 0.2,random_state=42)

In [43]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((24000,), (6000,), (24000,), (6000,))

In [44]:
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer()

In [45]:
x_train_vector = vector.fit_transform(x_train.values).toarray()

In [46]:
x_train_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
x_test_vector = vector.transform(x_test).toarray()

In [48]:
x_test_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(multi_class="multinomial")

In [50]:
model.fit(x_train_vector,y_train)

LogisticRegression(multi_class='multinomial')

In [51]:
y_pred = model.predict(x_test_vector)

In [52]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.8576666666666667
              precision    recall  f1-score   support

           0       0.77      0.88      0.82       904
           1       0.87      0.89      0.88      1506
           2       0.85      0.88      0.86      1527
           3       0.90      0.81      0.85      2063

    accuracy                           0.86      6000
   macro avg       0.85      0.86      0.85      6000
weighted avg       0.86      0.86      0.86      6000

[[ 796   27   40   41]
 [  56 1334   54   62]
 [  60   45 1347   75]
 [ 118  129  147 1669]]


''' 
To increase the accuracy of your model, especially since I used a very small dataset and its accuracy is currently 86%
for increase the accuracy of data to apply the following techniques:=
1) Add more data
2) L2 and L1 regularization
3) Hyperparameter Tuning 
 And so many techniques that increase the accuracy of our model'''

In [57]:
import pickle

pickle.dump(vector,open("vector.pkl","wb"))
pickle.dump(model,open("model.pkl","wb"))